version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/mydatabase
  db:
    image: mongo
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - db
    environment:
      - ME_CONFIG_MONGODB_SERVER=db

volumes:
  mongo-data:
